package chat

import (
	"github.com/blocknextai/go-packages/json"
	"github.com/blocknextai/platform-api/internal/nodeengine/domain/nodes"
	gjs "github.com/google/jsonschema-go/jsonschema"
)

type GeminiChatNode struct {
	nodes.Node
}

func NewGeminiChatNode(nodeID string) *GeminiChatNode {
	return &GeminiChatNode{
		Node: nodes.Node{
			ID:          nodeID,
			Version:     "0.0.1",
			Name:        "Gemini Chat",
			Description: "Generate a chat completion using Google Gemini.",
			Icon: nodes.NodeIcon{
				Brand: "gemini",
				Glyph: "chat",
			},
			Inputs: []nodes.NodeHandle{
				{Key: "in"},
			},
			Outputs: []nodes.NodeHandle{
				{Key: "out"},
			},
			Categories:    []string{"AI"},
			SubCategories: []string{"Gemini"},
			Tags: []string{
				"google",
				"ai",
				"llm",
				"chat",
				"completion",
				"generation",
			},
			SupportedCredentials: []string{
				"gemini_api",
			},
			InputSchema: &gjs.Schema{
				Type: "object",
				Properties: map[string]*gjs.Schema{
					"model": {
						Type:        "string",
						Title:       "Model",
						Description: "Gemini model identifier to use for the chat completion.",
						Enum: []any{
							"gemini-3.6-flash",
							"gemini-3.5-flash",
							"gemini-3.5-flash-lite",
							"gemini-3.1-pro-preview",
							"gemini-3.1-flash-lite",
							"gemini-3-flash-preview",
							"gemini-2.5-pro",
							"gemini-2.5-flash",
							"gemini-2.5-flash-lite",
						},
						Default: json.RawMessage(`"gemini-3.1-flash-lite"`),
					},
					"prompt": {
						Type:        "string",
						Title:       "Prompt",
						Description: "User prompt sent to the model.",
					},
					"temperature": {
						Type:        "number",
						Title:       "Temperature",
						Description: "Sampling temperature controlling randomness of the response.",
						Minimum:     new(0.0),
						Maximum:     new(2.0),
						Default:     json.RawMessage(`1`),
					},
				},
				Required: []string{
					"model",
					"prompt",
					"temperature",
				},
			},
			OutputSchema: &gjs.Schema{
				Type: "array",
				Items: &gjs.Schema{
					Type: "object",
					Properties: map[string]*gjs.Schema{
						"text": {
							Type:        "string",
							Description: "Text response generated by the model.",
						},
					},
				},
			},
			HasNaturalLanguage: true,
			Annotations: nodes.NodeAnnotations{
				ReadOnly:    true,
				Destructive: new(false),
			},
		},
	}
}
