version: 2

updates:
  - package-ecosystem: gomod
    directories:
      - /apps/platform-api
      - /apps/file-gateway-api
      - /packages/go-packages
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      go-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      bun-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directories:
      - /docker/*
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      docker-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      compose-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
