package chat

import (
	"github.com/blocknextai/go-packages/json"
	"github.com/blocknextai/platform-api/internal/nodeengine/domain/nodes"
	gjs "github.com/google/jsonschema-go/jsonschema"
)

type DeepseekChatNode struct {
	nodes.Node
}

func NewDeepseekChatNode(nodeID string) *DeepseekChatNode {
	return &DeepseekChatNode{
		Node: nodes.Node{
			ID:          nodeID,
			Kind:        nodes.NodeKindAction,
			Version:     "0.0.1",
			Name:        "DeepSeek Chat",
			Description: "Generate a chat completion using DeepSeek.",
			Icon: nodes.NodeIcon{
				Brand: "deepseek",
				Glyph: "chat",
			},
			Inputs: []nodes.NodeHandle{
				{Key: "in"},
			},
			Outputs: []nodes.NodeHandle{
				{Key: "out"},
			},
			Categories:    []string{"AI"},
			SubCategories: []string{"DeepSeek"},
			Tags: []string{
				"ai",
				"llm",
				"chat",
				"completion",
				"generation",
			},
			SupportedCredentials: []string{
				"deepseek_api",
			},
			InputSchema: &gjs.Schema{
				Type: "object",
				Properties: map[string]*gjs.Schema{
					"model": {
						Type:        "string",
						Title:       "Model",
						Description: "DeepSeek model identifier to use for the chat completion.",
						Enum: []any{
							"deepseek-v4-pro",
							"deepseek-v4-flash",
						},
						Default: json.RawMessage(`"deepseek-v4-flash"`),
					},
					"prompt": {
						Type:        "string",
						Title:       "Prompt",
						Description: "User prompt sent to the model.",
					},
				},
				Required: []string{
					"model",
					"prompt",
				},
			},
			OutputSchema: &gjs.Schema{
				Type: "array",
				Items: &gjs.Schema{
					Type: "object",
					Properties: map[string]*gjs.Schema{
						"text": {
							Type:        "string",
							Description: "Text response generated by the model.",
						},
					},
				},
			},
			HasNaturalLanguage: true,
			Annotations: nodes.NodeAnnotations{
				ReadOnly:    true,
				Destructive: new(false),
			},
		},
	}
}
