package chat

import (
	"github.com/blocknextai/go-packages/json"
	"github.com/blocknextai/platform-api/internal/nodeengine/domain/nodes"
	gjs "github.com/google/jsonschema-go/jsonschema"
)

type AnthropicChatNode struct {
	nodes.Node
}

func NewAnthropicChatNode(nodeID string) *AnthropicChatNode {
	return &AnthropicChatNode{
		Node: nodes.Node{
			ID:          nodeID,
			Kind:        nodes.NodeKindAction,
			Version:     "0.0.1",
			Name:        "Anthropic Chat",
			Description: "Generate a chat completion using Anthropic Claude.",
			Icon: nodes.NodeIcon{
				Brand: "anthropic",
				Glyph: "chat",
			},
			Inputs: []nodes.NodeHandle{
				{Key: "in"},
			},
			Outputs: []nodes.NodeHandle{
				{Key: "out"},
			},
			Categories:    []string{"AI"},
			SubCategories: []string{"Anthropic"},
			Tags: []string{
				"claude",
				"ai",
				"llm",
				"chat",
				"completion",
				"generation",
			},
			SupportedCredentials: []string{
				"anthropic_api",
			},
			InputSchema: &gjs.Schema{
				Type: "object",
				Properties: map[string]*gjs.Schema{
					"model": {
						Type:        "string",
						Title:       "Model",
						Description: "Anthropic Claude model identifier to use for the chat completion.",
						Enum: []any{
							"claude-fable-5",
							"claude-opus-5",
							"claude-sonnet-5",
							"claude-opus-4-8",
							"claude-opus-4-7",
							"claude-opus-4-6",
							"claude-sonnet-4-6",
							"claude-haiku-4-5",
						},
						Default: json.RawMessage(`"claude-haiku-4-5"`),
					},
					"maxTokens": {
						Type:        "number",
						Title:       "Max Tokens",
						Description: "Maximum number of tokens to generate in the response.",
						Default:     json.RawMessage(`1024`),
					},
					"prompt": {
						Type:        "string",
						Title:       "Prompt",
						Description: "User prompt sent to the model.",
					},
					"temperature": {
						Type:        "number",
						Title:       "Temperature",
						Description: "Sampling temperature controlling randomness of the response. Ignored by models that do not accept sampling parameters (Claude Fable 5, Opus 5, Sonnet 5, Opus 4.8, Opus 4.7).",
						Minimum:     new(0.0),
						Maximum:     new(1.0),
						Default:     json.RawMessage(`0.5`),
					},
				},
				Required: []string{
					"model",
					"maxTokens",
					"prompt",
					"temperature",
				},
			},
			OutputSchema: &gjs.Schema{
				Type: "array",
				Items: &gjs.Schema{
					Type: "object",
					Properties: map[string]*gjs.Schema{
						"text": {
							Type:        "string",
							Description: "Text response generated by the model.",
						},
					},
				},
			},
			HasNaturalLanguage: true,
			Annotations: nodes.NodeAnnotations{
				ReadOnly:    true,
				Destructive: new(false),
			},
		},
	}
}
