package chat

import (
	"github.com/blocknextai/go-packages/json"
	"github.com/blocknextai/platform-api/internal/nodeengine/domain/nodes"
	gjs "github.com/google/jsonschema-go/jsonschema"
)

type ChatgptChatNode struct {
	nodes.Node
}

func NewChatgptChatNode(nodeID string) *ChatgptChatNode {
	return &ChatgptChatNode{
		Node: nodes.Node{
			ID:          nodeID,
			Version:     "0.0.1",
			Name:        "ChatGPT Chat",
			Description: "Generate a chat completion using OpenAI ChatGPT.",
			Icon: nodes.NodeIcon{
				Brand: "chatgpt",
				Glyph: "chat",
			},
			Inputs: []nodes.NodeHandle{
				{Key: "in"},
			},
			Outputs: []nodes.NodeHandle{
				{Key: "out"},
			},
			Categories:    []string{"AI"},
			SubCategories: []string{"ChatGPT"},
			Tags: []string{
				"openai",
				"gpt",
				"ai",
				"llm",
				"chat",
				"completion",
			},
			SupportedCredentials: []string{
				"chatgpt_api",
			},
			InputSchema: &gjs.Schema{
				Type: "object",
				Properties: map[string]*gjs.Schema{
					"model": {
						Type:        "string",
						Title:       "Model",
						Description: "OpenAI model identifier to use for the chat completion.",
						Enum: []any{
							"gpt-5.6-sol",
							"gpt-5.6-terra",
							"gpt-5.6-luna",
							"gpt-5.5",
							"gpt-5.4",
							"gpt-5.4-mini",
							"gpt-5",
							"gpt-5-mini",
							"gpt-5-nano",
							"gpt-5-chat-latest",
						},
						Default: json.RawMessage(`"gpt-5.6-luna"`),
					},
					"prompt": {
						Type:        "string",
						Title:       "Prompt",
						Description: "User prompt sent to the model.",
					},
					"temperature": {
						Type:        "number",
						Title:       "Temperature",
						Description: "Sampling temperature controlling randomness of the response.",
						Minimum:     new(0.0),
						Maximum:     new(1.0),
						Default:     json.RawMessage(`0.5`),
					},
				},
				Required: []string{
					"model",
					"prompt",
					"temperature",
				},
			},
			OutputSchema: &gjs.Schema{
				Type: "array",
				Items: &gjs.Schema{
					Type: "object",
					Properties: map[string]*gjs.Schema{
						"text": {
							Type:        "string",
							Description: "Text response generated by the model.",
						},
					},
				},
			},
			HasNaturalLanguage: true,
			Annotations: nodes.NodeAnnotations{
				ReadOnly:    true,
				Destructive: new(false),
			},
		},
	}
}
