package nodes

import (
	"github.com/blocknextai/platform-api/internal/filegateway"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/airtable"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/anthropic"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/chatgpt"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/coingecko"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/deepl"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/deepseek"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/discord"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/elevenlabs"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/facebook"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/gemini"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/google/docs"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/google/drive"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/google/gmail"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/google/keep"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/google/sheets"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/google/youtube"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/instagram"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/linkedin"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/notion"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/piapi"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/sendgrid"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/slack"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/soundcloud"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/sunomusic"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/system"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/telegram"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/tiktok"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/veo"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/whatsapp"
	"github.com/blocknextai/platform-api/internal/modules/nodeengine/internal/nodes/x"
)

func Register(fileGatewayService filegateway.FileGateway) {
	gmail.Register()
	anthropic.Register()
	deepseek.Register()
	deepl.Register()
	chatgpt.Register()
	coingecko.Register()
	gemini.Register(fileGatewayService)
	piapi.Register()
	drive.Register(fileGatewayService)
	docs.Register()
	sheets.Register()
	telegram.Register()
	discord.Register(fileGatewayService)
	slack.Register(fileGatewayService)
	x.Register(fileGatewayService)
	instagram.Register()
	tiktok.Register(fileGatewayService)
	facebook.Register()
	youtube.Register(fileGatewayService)
	linkedin.Register(fileGatewayService)
	notion.Register()
	system.Register()
	sunomusic.Register()
	soundcloud.Register(fileGatewayService)
	elevenlabs.Register(fileGatewayService)
	veo.Register(fileGatewayService)
	whatsapp.Register()
	sendgrid.Register()
	airtable.Register()
	keep.Register()
}
